CREATE TABLE USUARIO(
	Login		VARCHAR(30) PRIMARY KEY,
	Email		VARCHAR(50) NOT NULL,
	Telefone	INT NOT NULL,
	Data_Nasc	DATE NOT NULL CHECK ( Data_Nasc <= '2002-01-01'), 
	Senha		VARCHAR(30) NOT NULL
);

CREATE TABLE INSTITUTO(
	CNPJ_Inst	INT PRIMARY KEY,
	Nome		VARCHAR(50) NOT NULL,
	CEP		INT NOT NULL,
	Num_End		INT NOT NULL,
	Logradouro	VARCHAR(100),
	Email		VARCHAR(50) NOT NULL
);

CREATE TABLE ALUNO(
	Login		VARCHAR(30) PRIMARY KEY,
	FOREIGN KEY (Login) REFERENCES USUARIO (Login)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ALUNO_FORA(
	Num_Aluno_Conv			INT PRIMARY KEY,
	Login				VARCHAR(30) NOT NULL,
	Faculdade			VARCHAR(50) NOT NULL,
	FOREIGN KEY (Login) REFERENCES ALUNO (Login)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ALUNO_USP(
	Num_USP			INT PRIMARY KEY,
	Login			VARCHAR(30) UNIQUE NOT NULL,
	CNPJ_Inst		INT UNIQUE,
	FOREIGN KEY (Login) REFERENCES ALUNO (Login)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (CNPJ_Inst) REFERENCES INSTITUTO (CNPJ_Inst)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CONVIDADO(
	Num_Conv		INT PRIMARY KEY,
	Login			VARCHAR(30) UNIQUE NOT NULL,
	Area_Trabalho		VARCHAR(50) NOT NULL,
	FOREIGN KEY (Login) REFERENCES USUARIO (Login)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PROFESSOR(
	Login				VARCHAR(30) PRIMARY KEY,
	Area_De_Atuacao		VARCHAR(30) NOT NULL,
	FOREIGN KEY (Login) REFERENCES USUARIO (Login)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PROF_FORA(
	Num_Prof_Conv			INT PRIMARY KEY,
	Login				VARCHAR(30) UNIQUE NOT NULL,
	Faculdade			VARCHAR(50) NOT NULL,
	FOREIGN KEY (Login) REFERENCES PROFESSOR (Login)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PROF_USP(
	Num_USP				INT PRIMARY KEY,
	Login				VARCHAR(30) UNIQUE NOT NULL,
	CNPJ_Inst			INT UNIQUE NOT NULL,
	FOREIGN KEY (Login) REFERENCES PROFESSOR (Login)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (CNPJ_Inst) REFERENCES INSTITUTO (CNPJ_Inst)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PALESTRANTE(
	Id_Palestrante			INT PRIMARY KEY,
	Disponibilidade			VARCHAR(500) NOT NULL,
	Login				VARCHAR(30) UNIQUE NOT NULL,
	FOREIGN KEY (Login) REFERENCES USUARIO (Login)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE LINGUA_PALESTRANTE(
	Lingua			VARCHAR(30) NOT NULL,
	Id_Palestrante		INT UNIQUE NOT NULL,
	PRIMARY KEY (Lingua,Id_Palestrante),
	FOREIGN KEY (Id_Palestrante) REFERENCES PALESTRANTE (Id_Palestrante)
		ON DELETE CASCADE ON UPDATE CASCADE
	
);

CREATE TABLE SALA(
	Identificador		VARCHAR(50) PRIMARY KEY,
	Bloco			VARCHAR(20) NOT NULL,
	Andar			INT NOT NULL,
	CNPJ_Inst		INT UNIQUE NOT NULL,
	FOREIGN KEY (CNPJ_Inst) REFERENCES INSTITUTO (CNPJ_Inst)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PALESTRA_FISICA(
	Id_Pale_Fisi		INT PRIMARY KEY,
	Titulo			VARCHAR(30) NOT NULL,
	Duracao			TIME NOT NULL,
	Horario			TIME NOT NULL,
	Data			DATE NOT NULL,
	Idioma_Palestra		VARCHAR(30) NOT NULL,
	Identificador		VARCHAR(50) NOT NULL,
	FOREIGN KEY (Identificador) REFERENCES SALA (Identificador)
		ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ASSISTE(
	Id_Pale_Fisi		INT,
	Login			VARCHAR(30),
	PRIMARY KEY (Login,Id_Pale_Fisi),
	FOREIGN KEY (Id_Pale_Fisi) REFERENCES PALESTRA_FISICA (Id_Pale_Fisi)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (Login) REFERENCES USUARIO (Login)
		ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE REALIZACAO(
	Id_Pale_Fisi		INT,
	Id_Palestrante		INT,
	PRIMARY KEY (Id_Palestrante,Id_Pale_Fisi),
	FOREIGN KEY (Id_Pale_Fisi) REFERENCES PALESTRA_FISICA (Id_Pale_Fisi)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (Id_Palestrante) REFERENCES PALESTRANTE (Id_Palestrante)
		ON DELETE CASCADE ON UPDATE CASCADE

);

CREATE TABLE TELEFONE_INSTITUTO(
	Telefone	INT NOT NULL,
	CNPJ_Inst	INT UNIQUE,
	FOREIGN KEY (CNPJ_Inst) REFERENCES INSTITUTO (CNPJ_Inst)
		ON DELETE CASCADE ON UPDATE CASCADE
);

